import { SmartBin, TruckAgent, CollectionRoute, Persona, MaintenanceTicket, ResidentReport, NegotiationBid, DeploymentArea } from './types';

export const INITIAL_SMART_BINS: SmartBin[] = [
  {
    id: 'BIN-101',
    name: 'Metro Plaza East',
    address: '42 Market Street, Downtown',
    district: 'Central Core',
    coords: { x: 22, y: 35, lat: 37.7749, lng: -122.4194 },
    fillLevel: 88,
    capacityLiters: 1200,
    wasteType: 'general',
    batteryLevel: 94,
    sensorStatus: 'optimal',
    lastEmptied: 'Yesterday, 18:30',
    bidPriority: 'critical',
    temperatureC: 21.4,
    odorPpm: 18,
    lidStatus: 'closed',
    currentBidAmount: 85,
    sensorAlerts: ['High fill rate (>15%/hr) during lunch rush'],
  },
  {
    id: 'BIN-102',
    name: 'Tech District Park',
    address: '108 Innovation Way, Sector 4',
    district: 'Innovation Hub',
    coords: { x: 38, y: 22, lat: 37.7811, lng: -122.4089 },
    fillLevel: 92,
    capacityLiters: 800,
    wasteType: 'recyclable',
    batteryLevel: 82,
    sensorStatus: 'optimal',
    lastEmptied: '2 days ago',
    bidPriority: 'critical',
    temperatureC: 19.8,
    odorPpm: 4,
    lidStatus: 'closed',
    currentBidAmount: 92,
    sensorAlerts: ['Capacity threshold >90% breached'],
  },
  {
    id: 'BIN-103',
    name: 'Botanical Promenade',
    address: '77 Garden Blvd, Green Belt',
    district: 'Eco Zone',
    coords: { x: 65, y: 28, lat: 37.7785, lng: -122.3951 },
    fillLevel: 78,
    capacityLiters: 1000,
    wasteType: 'organic',
    batteryLevel: 76,
    sensorStatus: 'warning',
    lastEmptied: 'Yesterday, 14:15',
    bidPriority: 'high',
    temperatureC: 28.5,
    odorPpm: 42,
    lidStatus: 'closed',
    currentBidAmount: 76,
    sensorAlerts: ['Elevated temperature & organic fermentation smell detected'],
  },
  {
    id: 'BIN-104',
    name: 'Harbor Gateway Pier 9',
    address: 'Pier 9 Maritime Boardwalk',
    district: 'Waterfront',
    coords: { x: 82, y: 40, lat: 37.7952, lng: -122.3937 },
    fillLevel: 64,
    capacityLiters: 1500,
    wasteType: 'general',
    batteryLevel: 98,
    sensorStatus: 'optimal',
    lastEmptied: 'Yesterday, 21:00',
    bidPriority: 'normal',
    temperatureC: 18.2,
    odorPpm: 8,
    lidStatus: 'closed',
    currentBidAmount: 58,
  },
  {
    id: 'BIN-105',
    name: 'University Quad South',
    address: '500 Campus Walk, Academic Hill',
    district: 'University District',
    coords: { x: 28, y: 70, lat: 37.7612, lng: -122.4350 },
    fillLevel: 84,
    capacityLiters: 900,
    wasteType: 'recyclable',
    batteryLevel: 68,
    sensorStatus: 'optimal',
    lastEmptied: 'Yesterday, 09:40',
    bidPriority: 'high',
    temperatureC: 20.1,
    odorPpm: 6,
    lidStatus: 'closed',
    currentBidAmount: 79,
  },
  {
    id: 'BIN-106',
    name: 'Civic Center Concourse',
    address: '300 Municipal Circle',
    district: 'Central Core',
    coords: { x: 45, y: 52, lat: 37.7710, lng: -122.4168 },
    fillLevel: 51,
    capacityLiters: 1200,
    wasteType: 'general',
    batteryLevel: 89,
    sensorStatus: 'optimal',
    lastEmptied: 'Today, 06:15',
    bidPriority: 'normal',
    temperatureC: 20.5,
    odorPpm: 9,
    lidStatus: 'closed',
    currentBidAmount: 45,
  },
  {
    id: 'BIN-107',
    name: 'Artisan Alley Arts Hub',
    address: '15 Gallery Row, Creative Quarter',
    district: 'Cultural Quarter',
    coords: { x: 58, y: 68, lat: 37.7650, lng: -122.4080 },
    fillLevel: 35,
    capacityLiters: 800,
    wasteType: 'hazardous',
    batteryLevel: 54,
    sensorStatus: 'warning',
    lastEmptied: '3 days ago',
    bidPriority: 'low',
    temperatureC: 22.0,
    odorPpm: 12,
    lidStatus: 'closed',
    currentBidAmount: 32,
    sensorAlerts: ['Battery below 55% - solar charge low'],
  },
  {
    id: 'BIN-108',
    name: 'Grand Central Station Exit',
    address: '1 Station Square, Transit Center',
    district: 'Transit Hub',
    coords: { x: 42, y: 38, lat: 37.7790, lng: -122.4140 },
    fillLevel: 95,
    capacityLiters: 1600,
    wasteType: 'general',
    batteryLevel: 91,
    sensorStatus: 'optimal',
    lastEmptied: 'Today, 05:30',
    bidPriority: 'critical',
    temperatureC: 22.8,
    odorPpm: 26,
    lidStatus: 'open',
    currentBidAmount: 98,
    sensorAlerts: ['Lid stuck open, potential spill hazard'],
  },
  {
    id: 'BIN-109',
    name: 'Eco-Living Residential West',
    address: '88 Meadow Lane, Green Heights',
    district: 'Residential Park',
    coords: { x: 15, y: 60, lat: 37.7580, lng: -122.4450 },
    fillLevel: 42,
    capacityLiters: 1100,
    wasteType: 'organic',
    batteryLevel: 88,
    sensorStatus: 'optimal',
    lastEmptied: 'Yesterday, 11:20',
    bidPriority: 'low',
    temperatureC: 17.5,
    odorPpm: 14,
    lidStatus: 'closed',
    currentBidAmount: 38,
  },
  {
    id: 'BIN-110',
    name: 'Marina Yacht Basin',
    address: '22 Harbor Light Dr, Bayfront',
    district: 'Waterfront',
    coords: { x: 78, y: 18, lat: 37.8020, lng: -122.4200 },
    fillLevel: 73,
    capacityLiters: 900,
    wasteType: 'recyclable',
    batteryLevel: 79,
    sensorStatus: 'optimal',
    lastEmptied: 'Yesterday, 16:00',
    bidPriority: 'high',
    temperatureC: 18.0,
    odorPpm: 5,
    lidStatus: 'closed',
    currentBidAmount: 70,
  },
  {
    id: 'BIN-111',
    name: 'Industrial Logistics Depot',
    address: '900 Freight Road, East Yard',
    district: 'Industrial East',
    coords: { x: 88, y: 75, lat: 37.7550, lng: -122.3850 },
    fillLevel: 28,
    capacityLiters: 2000,
    wasteType: 'hazardous',
    batteryLevel: 95,
    sensorStatus: 'optimal',
    lastEmptied: '4 days ago',
    bidPriority: 'low',
    temperatureC: 19.1,
    odorPpm: 3,
    lidStatus: 'closed',
    currentBidAmount: 25,
  },
  {
    id: 'BIN-112',
    name: 'Midtown Shopping Arcade',
    address: '220 Fashion Ave, Retail Row',
    district: 'Central Core',
    coords: { x: 32, y: 48, lat: 37.7680, lng: -122.4220 },
    fillLevel: 81,
    capacityLiters: 1000,
    wasteType: 'general',
    batteryLevel: 85,
    sensorStatus: 'optimal',
    lastEmptied: 'Yesterday, 17:10',
    bidPriority: 'high',
    temperatureC: 21.0,
    odorPpm: 15,
    lidStatus: 'closed',
    currentBidAmount: 77,
  },
];

export const INITIAL_TRUCK_AGENTS: TruckAgent[] = [
  {
    id: 'TRUCK-01',
    name: 'Unit Alpha',
    model: 'Volvo FE Electric Autonomous Compactor',
    powertrain: 'Electric EV',
    maxPayloadKg: 6500,
    currentLoadKg: 2840,
    batteryLevel: 82,
    status: 'routing',
    coords: { x: 26, y: 36 },
    targetCoords: { x: 38, y: 22 },
    speedKmh: 24,
    assignedRouteId: 'ROUTE-2026-091',
    completedPickups: 2,
    efficiencyRating: 96.4,
    roboticArmStatus: 'ready',
    driverAgentMode: 'autonomous',
  },
  {
    id: 'TRUCK-02',
    name: 'Unit Beta',
    model: 'Mack LR Electric Heavy Hauler',
    powertrain: 'Electric EV',
    maxPayloadKg: 8000,
    currentLoadKg: 1200,
    batteryLevel: 91,
    status: 'idle',
    coords: { x: 50, y: 50 },
    speedKmh: 0,
    assignedRouteId: null,
    completedPickups: 0,
    efficiencyRating: 98.1,
    roboticArmStatus: 'retracted',
    driverAgentMode: 'autonomous',
  },
  {
    id: 'TRUCK-03',
    name: 'Unit Gamma',
    model: 'Hyzon Hydrogen Compact Urban Rover',
    powertrain: 'Hydrogen Hybrid',
    maxPayloadKg: 4200,
    currentLoadKg: 3800,
    batteryLevel: 45,
    status: 'returning',
    coords: { x: 72, y: 60 },
    targetCoords: { x: 50, y: 50 },
    speedKmh: 31,
    assignedRouteId: 'ROUTE-2026-089',
    completedPickups: 5,
    efficiencyRating: 93.8,
    roboticArmStatus: 'retracted',
    driverAgentMode: 'autonomous',
  },
];

export const INITIAL_PERSONAS: Persona[] = [
  {
    role: 'Operations Supervisor',
    name: 'Elena Vance',
    badge: 'HQ Operations Lead',
    channel: 'Supervisory Dispatch & Analytics',
    description: 'Monitors fleet KPIs, fuel/CO2 emissions, overrides automated route auctions, and approves daily schedules.',
  },
  {
    role: 'Driver Agent',
    name: 'Autonomous Agent T-01 (HUD)',
    badge: 'Teleoperation Telemetry',
    channel: 'In-Cab Augmented Telematics & Arm Telemetry',
    description: 'Real-time vehicle driving corridor, robotic arm pickup handshake, on-board payload scales, and route guidance.',
  },
  {
    role: 'Maintenance Technician',
    name: 'Marcus Brody',
    badge: 'Field Robotic Tech',
    channel: 'Diagnostic Station & Sensor Telemetry',
    description: 'Calibrates smart bin ultrasonic sensors, checks lidar/camera arrays on trucks, and manages battery health.',
  },
  {
    role: 'City Resident',
    name: 'Sarah Chen (Civic Portal)',
    badge: 'Eco-Citizen #4092',
    channel: 'Public Mobile Web App',
    description: 'Views neighborhood bin fill status, requests special pickups for bulky/e-waste items, and earns clean city credits.',
  },
  {
    role: 'Server Controller',
    name: 'Central Server Controller (AI Orchestrator)',
    badge: 'Dispatch & Replacements',
    channel: 'Autonomous Algorithmic Service Bus & Event Stream',
    description: 'Receives citizen reports, executes smart bin replacements, and coordinates multi-agent autonomous truck auctions.',
  },
];

export const INITIAL_ROUTE: CollectionRoute = {
  routeId: 'ROUTE-2026-091',
  truckId: 'TRUCK-01',
  truckName: 'Unit Alpha (Electric Compactor)',
  scheduledDate: '2026-09-17',
  status: 'active',
  waypoints: [
    {
      id: 'WP-1',
      binId: 'BIN-108',
      binName: 'Grand Central Station Exit',
      address: '1 Station Square, Transit Center',
      coords: { x: 42, y: 38 },
      fillLevelSnapshot: 95,
      wasteType: 'general',
      estimatedWeightKg: 780,
      distanceFromPrevKm: 2.1,
      etaMinutes: 6,
      status: 'completed',
      collectedWeightKg: 810,
      servicedAt: '09:12 AM',
    },
    {
      id: 'WP-2',
      binId: 'BIN-101',
      binName: 'Metro Plaza East',
      address: '42 Market Street, Downtown',
      coords: { x: 22, y: 35 },
      fillLevelSnapshot: 88,
      wasteType: 'general',
      estimatedWeightKg: 620,
      distanceFromPrevKm: 1.8,
      etaMinutes: 5,
      status: 'completed',
      collectedWeightKg: 640,
      servicedAt: '09:28 AM',
    },
    {
      id: 'WP-3',
      binId: 'BIN-102',
      binName: 'Tech District Park',
      address: '108 Innovation Way, Sector 4',
      coords: { x: 38, y: 22 },
      fillLevelSnapshot: 92,
      wasteType: 'recyclable',
      estimatedWeightKg: 490,
      distanceFromPrevKm: 2.6,
      etaMinutes: 8,
      status: 'approaching',
    },
    {
      id: 'WP-4',
      binId: 'BIN-112',
      binName: 'Midtown Shopping Arcade',
      address: '220 Fashion Ave, Retail Row',
      coords: { x: 32, y: 48 },
      fillLevelSnapshot: 81,
      wasteType: 'general',
      estimatedWeightKg: 520,
      distanceFromPrevKm: 2.2,
      etaMinutes: 14,
      status: 'pending',
    },
    {
      id: 'WP-5',
      binId: 'BIN-105',
      binName: 'University Quad South',
      address: '500 Campus Walk, Academic Hill',
      coords: { x: 28, y: 70 },
      fillLevelSnapshot: 84,
      wasteType: 'recyclable',
      estimatedWeightKg: 430,
      distanceFromPrevKm: 3.1,
      etaMinutes: 22,
      status: 'pending',
    },
  ],
  totalDistanceKm: 11.8,
  estimatedFuelLitres: 0, // 100% Electric
  actualEnergyKwh: 14.2,
  co2SavedKg: 38.6,
  efficiencyScore: 94.8,
  activeWaypointIndex: 2,
  negotiationSessionId: 'NEG-SESSION-8841',
  aiOptimizationRationale: 'Multi-agent auction resolved: Bins BIN-108, BIN-101, BIN-102 prioritized due to >85% fill urgency. Truck Unit Alpha awarded route based on closest proximity (2.1km depot delta) and 72% battery reserve margin.',
};

export const INITIAL_BIDS: NegotiationBid[] = [
  {
    id: 'BID-901',
    timestamp: '09:02:14',
    binId: 'BIN-108',
    binName: 'Grand Central Station Exit',
    truckId: 'TRUCK-01',
    truckName: 'Unit Alpha',
    binFillLevel: 95,
    urgencyScore: 98,
    proposedCostMetric: 12.4,
    status: 'accepted',
    rationale: 'Critical fill level 95% + open lid hazard. Highest bid priority awarded to Unit Alpha.',
  },
  {
    id: 'BID-902',
    timestamp: '09:02:18',
    binId: 'BIN-102',
    binName: 'Tech District Park',
    truckId: 'TRUCK-01',
    truckName: 'Unit Alpha',
    binFillLevel: 92,
    urgencyScore: 92,
    proposedCostMetric: 14.1,
    status: 'accepted',
    rationale: 'Clustered along Northern corridor; minimal marginal battery penalty (0.8 kWh).',
  },
  {
    id: 'BID-903',
    timestamp: '09:02:22',
    binId: 'BIN-103',
    binName: 'Botanical Promenade',
    truckId: 'TRUCK-02',
    truckName: 'Unit Beta',
    binFillLevel: 78,
    urgencyScore: 76,
    proposedCostMetric: 22.8,
    status: 'truck_evaluated',
    rationale: 'Organic waste stream. Counter-offer pending Unit Beta scheduled morning dispatch.',
  },
  {
    id: 'BID-904',
    timestamp: '09:02:30',
    binId: 'BIN-107',
    binName: 'Artisan Alley Arts Hub',
    truckId: 'TRUCK-01',
    truckName: 'Unit Alpha',
    binFillLevel: 35,
    urgencyScore: 32,
    proposedCostMetric: 39.5,
    status: 'declined',
    rationale: 'Marginal fuel cost exceeds urgency benefit. Deferred to next negotiation cycle.',
  },
];

export const INITIAL_TICKETS: MaintenanceTicket[] = [
  {
    id: 'TCK-401',
    targetType: 'smart_bin',
    targetId: 'BIN-108',
    targetName: 'Grand Central Station Exit',
    severity: 'high',
    component: 'Pneumatic Lid Hinge & Seal',
    issueDescription: 'Lid stuck at 45 degree angle. Motor stall detected in optical sensor.',
    reportedAt: 'Today, 08:15',
    status: 'in_progress',
    recommendedAction: 'Dispatch field tech to clear obstruction and lubricate servo shaft.',
  },
  {
    id: 'TCK-402',
    targetType: 'smart_bin',
    targetId: 'BIN-103',
    targetName: 'Botanical Promenade',
    severity: 'medium',
    component: 'VOC Odor Gas Sensor Array',
    issueDescription: 'Odor sensor drift detected: baseline reading exceeds 40 ppm calibration threshold.',
    reportedAt: 'Yesterday, 17:30',
    status: 'open',
    recommendedAction: 'Recalibrate gas sensor probe and inspect organic filter baffle.',
  },
  {
    id: 'TCK-403',
    targetType: 'truck_agent',
    targetId: 'TRUCK-01',
    targetName: 'Unit Alpha',
    severity: 'low',
    component: 'Robotic Arm Optical Scale Tare',
    issueDescription: 'Weight delta drift (+/- 4.2 kg) on bin grip verification.',
    reportedAt: '2 days ago',
    status: 'calibrated',
    recommendedAction: 'Zero load-cell calibration completed during night shift recharge.',
  },
];

export const INITIAL_RESIDENT_REPORTS: ResidentReport[] = [
  {
    id: 'REP-701',
    residentName: 'Carlos Ramirez',
    binId: 'BIN-108',
    type: 'lid_stuck',
    description: 'Cardboard box caught in upper lid hinge preventing full auto-seal.',
    timestamp: '08:10 AM',
    rewardPoints: 25,
    status: 'approved',
  },
  {
    id: 'REP-702',
    residentName: 'Aisha Patel',
    binId: 'BIN-105',
    type: 'bulky_item_request',
    description: 'Requesting on-demand pickup for 2 discarded university study desks.',
    timestamp: '07:45 AM',
    rewardPoints: 50,
    status: 'scheduled',
  },
  {
    id: 'REP-703',
    residentName: 'Liam O’Connor',
    binId: 'BIN-103',
    type: 'odor_complaint',
    description: 'Compost smell noticeable along walking trail near botanical gardens.',
    timestamp: 'Yesterday',
    rewardPoints: 15,
    status: 'resolved',
  },
];

export const DEPLOYMENT_AREAS: DeploymentArea[] = [
  {
    id: 'downtown_metro',
    name: 'Metropolis Downtown & Central Core',
    tagline: 'High-density commercial avenues, transit hubs, and retail thoroughfares',
    city: 'Metropolis Central',
    category: 'urban_metro',
    description: 'High-density commercial avenues and transit terminals prone to rapid midday waste spikes. Deploys agile Volvo FE electric compactors with zero tailpipe emissions and sound-dampened robotic lifters for narrow urban alleys.',
    population: '124,000 workers & visitors',
    dailyWasteEstKg: 28400,
    activeSensorsCount: 12,
    recommendedFleet: 'Unit Alpha (Volvo FE) + Unit Beta (Mack LR) + Unit Gamma (Hyzon)',
    areaKm2: 8.5,
    accentColor: '#10b981', // emerald
    zones: [
      {
        name: 'CENTRAL CORE',
        points: '20,25 55,25 55,60 20,60',
        color: '#0ea5e9',
        fillOpacity: 0.15,
        labelCoords: { x: 22, y: 29 },
      },
      {
        name: 'WATERFRONT',
        points: '70,0 100,0 100,100 75,100',
        color: '#38bdf8',
        fillOpacity: 0.12,
        labelCoords: { x: 80, y: 8 },
      },
      {
        name: 'ECO-PARK',
        points: '55,15 85,15 85,45 55,45',
        color: '#10b981',
        fillOpacity: 0.12,
        labelCoords: { x: 60, y: 19 },
      },
      {
        name: 'TRANSIT & CAMPUS',
        points: '10,62 40,62 40,92 10,92',
        color: '#8b5cf6',
        fillOpacity: 0.12,
        labelCoords: { x: 12, y: 66 },
      },
    ],
    bins: INITIAL_SMART_BINS,
    trucks: INITIAL_TRUCK_AGENTS,
    initialRoute: INITIAL_ROUTE,
  },
  {
    id: 'waterfront_marina',
    name: 'Bayfront Marina & Coastal Promenade',
    tagline: 'Scenic seaside boardwalks, marina slips, and tourist waterfront piers',
    city: 'Bayfront Ocean District',
    category: 'coastal_waterfront',
    description: 'High pedestrian footfall along seaside promenades and dining piers. Smart bins feature automated solar compaction and seagull-proof motorized lids, serviced by whisper-quiet electric maritime haulers.',
    population: '46,000 visitors & boaters',
    dailyWasteEstKg: 16800,
    activeSensorsCount: 8,
    recommendedFleet: 'Unit Nautilus (Electric Coastal) + Unit Marina-02',
    areaKm2: 5.2,
    accentColor: '#06b6d4', // cyan
    zones: [
      {
        name: 'HARBOR BASIN & SLIPS',
        points: '10,20 60,15 65,55 15,60',
        color: '#06b6d4',
        fillOpacity: 0.2,
        labelCoords: { x: 18, y: 25 },
      },
      {
        name: 'BOARDWALK ESPLANADE',
        points: '60,10 95,10 95,90 60,85',
        color: '#0284c7',
        fillOpacity: 0.18,
        labelCoords: { x: 68, y: 18 },
      },
      {
        name: 'SEASIDE ECO-DUNES',
        points: '15,65 55,65 55,95 15,95',
        color: '#14b8a6',
        fillOpacity: 0.15,
        labelCoords: { x: 20, y: 72 },
      },
    ],
    bins: [
      {
        id: 'MBIN-201',
        name: 'Pier 7 Fisherman’s Basin',
        address: '700 Harbor Way, Pier 7',
        district: 'Boardwalk Esplanade',
        coords: { x: 74, y: 22, lat: 37.8012, lng: -122.4045 },
        fillLevel: 94,
        capacityLiters: 1500,
        wasteType: 'general',
        batteryLevel: 98,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 19:00',
        bidPriority: 'critical',
        temperatureC: 18.5,
        odorPpm: 24,
        lidStatus: 'closed',
        currentBidAmount: 92,
        sensorAlerts: ['High tourist footfall deposit rate'],
      },
      {
        id: 'MBIN-202',
        name: 'Marina Yacht Club Slip 12',
        address: '120 Marina Blvd, Dock Gate C',
        district: 'Harbor Basin & Slips',
        coords: { x: 35, y: 28, lat: 37.8045, lng: -122.4350 },
        fillLevel: 62,
        capacityLiters: 1000,
        wasteType: 'recyclable',
        batteryLevel: 88,
        sensorStatus: 'optimal',
        lastEmptied: 'Today, 06:00',
        bidPriority: 'normal',
        temperatureC: 17.2,
        odorPpm: 5,
        lidStatus: 'closed',
        currentBidAmount: 52,
      },
      {
        id: 'MBIN-203',
        name: 'Seaside Lighthouse Pavilion',
        address: '1 Lighthouse Point Lookout',
        district: 'Seaside Eco-Dunes',
        coords: { x: 28, y: 78, lat: 37.8102, lng: -122.4410 },
        fillLevel: 86,
        capacityLiters: 1200,
        wasteType: 'organic',
        batteryLevel: 92,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 14:00',
        bidPriority: 'high',
        temperatureC: 19.1,
        odorPpm: 31,
        lidStatus: 'closed',
        currentBidAmount: 84,
        sensorAlerts: ['Organic compost threshold nearing 90%'],
      },
      {
        id: 'MBIN-204',
        name: 'Ferry Terminal Departure Hall',
        address: '2 Bay Gate Center',
        district: 'Boardwalk Esplanade',
        coords: { x: 82, y: 48, lat: 37.7955, lng: -122.3935 },
        fillLevel: 79,
        capacityLiters: 1800,
        wasteType: 'recyclable',
        batteryLevel: 95,
        sensorStatus: 'optimal',
        lastEmptied: 'Today, 07:30',
        bidPriority: 'high',
        temperatureC: 20.0,
        odorPpm: 8,
        lidStatus: 'closed',
        currentBidAmount: 76,
      },
      {
        id: 'MBIN-205',
        name: 'Oceanside Amphitheater Plaza',
        address: '55 Festival Pier Walk',
        district: 'Boardwalk Esplanade',
        coords: { x: 80, y: 72, lat: 37.7890, lng: -122.3890 },
        fillLevel: 100,
        capacityLiters: 1400,
        wasteType: 'general',
        batteryLevel: 89,
        sensorStatus: 'optimal',
        lastEmptied: '2 days ago',
        bidPriority: 'critical',
        temperatureC: 22.4,
        odorPpm: 38,
        lidStatus: 'open',
        currentBidAmount: 100,
        sensorAlerts: ['100% Full: Autonomous Zero-Overflow Mandate Triggered'],
      },
      {
        id: 'MBIN-206',
        name: 'Pelican Cove Kayak Launch',
        address: '10 Estuary Way',
        district: 'Harbor Basin & Slips',
        coords: { x: 42, y: 48, lat: 37.8010, lng: -122.4280 },
        fillLevel: 45,
        capacityLiters: 900,
        wasteType: 'organic',
        batteryLevel: 78,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 11:00',
        bidPriority: 'low',
        temperatureC: 18.0,
        odorPpm: 12,
        lidStatus: 'closed',
        currentBidAmount: 39,
      },
      {
        id: 'MBIN-207',
        name: 'Maritime Heritage Center',
        address: '350 Historic Wharf',
        district: 'Harbor Basin & Slips',
        coords: { x: 22, y: 38, lat: 37.8070, lng: -122.4180 },
        fillLevel: 58,
        capacityLiters: 1100,
        wasteType: 'hazardous',
        batteryLevel: 84,
        sensorStatus: 'warning',
        lastEmptied: '3 days ago',
        bidPriority: 'normal',
        temperatureC: 17.8,
        odorPpm: 7,
        lidStatus: 'closed',
        currentBidAmount: 55,
      },
      {
        id: 'MBIN-208',
        name: 'Sunset View Coastal Park',
        address: '400 Shoreline Drive',
        district: 'Seaside Eco-Dunes',
        coords: { x: 45, y: 85, lat: 37.7850, lng: -122.4490 },
        fillLevel: 71,
        capacityLiters: 1000,
        wasteType: 'recyclable',
        batteryLevel: 91,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 16:30',
        bidPriority: 'high',
        temperatureC: 19.3,
        odorPpm: 10,
        lidStatus: 'closed',
        currentBidAmount: 68,
      },
    ],
    trucks: [
      {
        id: 'TRUCK-M01',
        name: 'Unit Nautilus',
        model: 'Mack LR Electric Coastal Hauler',
        powertrain: 'Electric EV',
        maxPayloadKg: 7200,
        currentLoadKg: 2100,
        batteryLevel: 89,
        status: 'routing',
        coords: { x: 74, y: 35 },
        targetCoords: { x: 80, y: 72 },
        speedKmh: 22,
        assignedRouteId: 'ROUTE-MARINA-01',
        completedPickups: 1,
        efficiencyRating: 97.2,
        roboticArmStatus: 'ready',
        driverAgentMode: 'autonomous',
      },
      {
        id: 'TRUCK-M02',
        name: 'Unit Breeze',
        model: 'Volvo FE Electric Whisper-Quiet',
        powertrain: 'Electric EV',
        maxPayloadKg: 6000,
        currentLoadKg: 850,
        batteryLevel: 94,
        status: 'idle',
        coords: { x: 30, y: 25 },
        speedKmh: 0,
        assignedRouteId: null,
        completedPickups: 0,
        efficiencyRating: 98.6,
        roboticArmStatus: 'retracted',
        driverAgentMode: 'autonomous',
      },
    ],
    initialRoute: {
      routeId: 'ROUTE-MARINA-01',
      truckId: 'TRUCK-M01',
      truckName: 'Unit Nautilus (Electric Coastal)',
      scheduledDate: '2026-09-24',
      status: 'active',
      waypoints: [
        {
          id: 'MWP-1',
          binId: 'MBIN-205',
          binName: 'Oceanside Amphitheater Plaza',
          address: '55 Festival Pier Walk',
          coords: { x: 80, y: 72 },
          fillLevelSnapshot: 100,
          wasteType: 'general',
          estimatedWeightKg: 910,
          distanceFromPrevKm: 1.6,
          etaMinutes: 4,
          status: 'approaching',
        },
        {
          id: 'MWP-2',
          binId: 'MBIN-201',
          binName: 'Pier 7 Fisherman’s Basin',
          address: '700 Harbor Way, Pier 7',
          coords: { x: 74, y: 22 },
          fillLevelSnapshot: 94,
          wasteType: 'general',
          estimatedWeightKg: 820,
          distanceFromPrevKm: 2.3,
          etaMinutes: 6,
          status: 'pending',
        },
        {
          id: 'MWP-3',
          binId: 'MBIN-203',
          binName: 'Seaside Lighthouse Pavilion',
          address: '1 Lighthouse Point Lookout',
          coords: { x: 28, y: 78 },
          fillLevelSnapshot: 86,
          wasteType: 'organic',
          estimatedWeightKg: 710,
          distanceFromPrevKm: 3.1,
          etaMinutes: 8,
          status: 'pending',
        },
      ],
      totalDistanceKm: 7.0,
      estimatedFuelLitres: 0,
      actualEnergyKwh: 12.8,
      co2SavedKg: 28.5,
      efficiencyScore: 97.4,
      activeWaypointIndex: 0,
      aiOptimizationRationale: 'Marina Coastal Route prioritized MBIN-205 (100% capacity mandate) and seaside boardwalk bins before evening sunset crowds arrive.',
    },
  },
  {
    id: 'suburban_greenbelt',
    name: 'Greenwood Valley & Suburban Eco-District',
    tagline: 'Quiet suburban neighborhoods, eco-schools, and residential composting centers',
    city: 'Greenwood Valley',
    category: 'suburban_residential',
    description: 'Sprawling residential neighborhoods and community parks emphasizing organic composting and high-grade recyclables. Uses long-range hydrogen-hybrid haulers calibrated for scheduled morning quiet-hour collection.',
    population: '78,000 residents',
    dailyWasteEstKg: 31200,
    activeSensorsCount: 8,
    recommendedFleet: 'Unit Green-1 (Hydrogen Heavy Hauler) + Unit Eco-2',
    areaKm2: 14.8,
    accentColor: '#10b981', // emerald
    zones: [
      {
        name: 'PINECREST NORTH HOA',
        points: '10,10 50,10 50,45 10,45',
        color: '#10b981',
        fillOpacity: 0.18,
        labelCoords: { x: 15, y: 16 },
      },
      {
        name: 'VALLEY OAK ESTATES',
        points: '55,10 90,10 90,55 55,55',
        color: '#059669',
        fillOpacity: 0.16,
        labelCoords: { x: 60, y: 16 },
      },
      {
        name: 'COMMUNITY RECREATION PARK',
        points: '20,55 80,55 80,92 20,92',
        color: '#14b8a6',
        fillOpacity: 0.15,
        labelCoords: { x: 30, y: 62 },
      },
    ],
    bins: [
      {
        id: 'GBIN-301',
        name: 'Pinecrest Community Center',
        address: '100 Pinecrest Blvd',
        district: 'PINECREST NORTH HOA',
        coords: { x: 25, y: 22, lat: 37.7410, lng: -122.4610 },
        fillLevel: 89,
        capacityLiters: 1200,
        wasteType: 'organic',
        batteryLevel: 94,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 10:00',
        bidPriority: 'critical',
        temperatureC: 22.1,
        odorPpm: 28,
        lidStatus: 'closed',
        currentBidAmount: 88,
        sensorAlerts: ['High garden compost volume'],
      },
      {
        id: 'GBIN-302',
        name: 'Valley Oak Elementary School',
        address: '450 Oak Tree Lane',
        district: 'VALLEY OAK ESTATES',
        coords: { x: 72, y: 25, lat: 37.7460, lng: -122.4510 },
        fillLevel: 92,
        capacityLiters: 1100,
        wasteType: 'recyclable',
        batteryLevel: 87,
        sensorStatus: 'optimal',
        lastEmptied: '2 days ago',
        bidPriority: 'critical',
        temperatureC: 19.4,
        odorPpm: 6,
        lidStatus: 'closed',
        currentBidAmount: 90,
      },
      {
        id: 'GBIN-303',
        name: 'Meadow Vista Sports Complex',
        address: '88 Meadow Road',
        district: 'COMMUNITY RECREATION PARK',
        coords: { x: 48, y: 70, lat: 37.7380, lng: -122.4550 },
        fillLevel: 82,
        capacityLiters: 1500,
        wasteType: 'general',
        batteryLevel: 96,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 17:00',
        bidPriority: 'high',
        temperatureC: 21.0,
        odorPpm: 14,
        lidStatus: 'closed',
        currentBidAmount: 78,
      },
      {
        id: 'GBIN-304',
        name: 'Willow Creek Trailhead',
        address: '12 Creek View Point',
        district: 'COMMUNITY RECREATION PARK',
        coords: { x: 28, y: 82, lat: 37.7320, lng: -122.4630 },
        fillLevel: 48,
        capacityLiters: 800,
        wasteType: 'organic',
        batteryLevel: 75,
        sensorStatus: 'optimal',
        lastEmptied: 'Today, 06:15',
        bidPriority: 'low',
        temperatureC: 17.5,
        odorPpm: 9,
        lidStatus: 'closed',
        currentBidAmount: 42,
      },
      {
        id: 'GBIN-305',
        name: 'Sunset Ridge Farmers Market',
        address: '300 Village Square',
        district: 'VALLEY OAK ESTATES',
        coords: { x: 80, y: 45, lat: 37.7420, lng: -122.4480 },
        fillLevel: 78,
        capacityLiters: 1600,
        wasteType: 'organic',
        batteryLevel: 91,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 19:30',
        bidPriority: 'high',
        temperatureC: 23.5,
        odorPpm: 34,
        lidStatus: 'closed',
        currentBidAmount: 81,
      },
      {
        id: 'GBIN-306',
        name: 'Cedar Grove Library Hub',
        address: '600 Civic Court',
        district: 'PINECREST NORTH HOA',
        coords: { x: 38, y: 38, lat: 37.7440, lng: -122.4580 },
        fillLevel: 55,
        capacityLiters: 1000,
        wasteType: 'recyclable',
        batteryLevel: 90,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 14:00',
        bidPriority: 'normal',
        temperatureC: 18.2,
        odorPpm: 4,
        lidStatus: 'closed',
        currentBidAmount: 51,
      },
    ],
    trucks: [
      {
        id: 'TRUCK-G01',
        name: 'Unit Green-1',
        model: 'Hyzon Hydrogen High-Capacity Compactor',
        powertrain: 'Hydrogen Hybrid',
        maxPayloadKg: 8500,
        currentLoadKg: 3100,
        batteryLevel: 92,
        status: 'routing',
        coords: { x: 30, y: 25 },
        targetCoords: { x: 72, y: 25 },
        speedKmh: 35,
        assignedRouteId: 'ROUTE-GREEN-01',
        completedPickups: 1,
        efficiencyRating: 98.4,
        roboticArmStatus: 'ready',
        driverAgentMode: 'autonomous',
      },
      {
        id: 'TRUCK-G02',
        name: 'Unit Eco-2',
        model: 'Volvo FE Electric Suburban Hauler',
        powertrain: 'Electric EV',
        maxPayloadKg: 6500,
        currentLoadKg: 950,
        batteryLevel: 96,
        status: 'idle',
        coords: { x: 50, y: 60 },
        speedKmh: 0,
        assignedRouteId: null,
        completedPickups: 0,
        efficiencyRating: 99.1,
        roboticArmStatus: 'retracted',
        driverAgentMode: 'autonomous',
      },
    ],
    initialRoute: {
      routeId: 'ROUTE-GREEN-01',
      truckId: 'TRUCK-G01',
      truckName: 'Unit Green-1 (Hydrogen Compactor)',
      scheduledDate: '2026-09-24',
      status: 'active',
      waypoints: [
        {
          id: 'GWP-1',
          binId: 'GBIN-302',
          binName: 'Valley Oak Elementary School',
          address: '450 Oak Tree Lane',
          coords: { x: 72, y: 25 },
          fillLevelSnapshot: 92,
          wasteType: 'recyclable',
          estimatedWeightKg: 780,
          distanceFromPrevKm: 2.8,
          etaMinutes: 7,
          status: 'approaching',
        },
        {
          id: 'GWP-2',
          binId: 'GBIN-301',
          binName: 'Pinecrest Community Center',
          address: '100 Pinecrest Blvd',
          coords: { x: 25, y: 22 },
          fillLevelSnapshot: 89,
          wasteType: 'organic',
          estimatedWeightKg: 820,
          distanceFromPrevKm: 3.2,
          etaMinutes: 8,
          status: 'pending',
        },
        {
          id: 'GWP-3',
          binId: 'GBIN-303',
          binName: 'Meadow Vista Sports Complex',
          address: '88 Meadow Road',
          coords: { x: 48, y: 70 },
          fillLevelSnapshot: 82,
          wasteType: 'general',
          estimatedWeightKg: 950,
          distanceFromPrevKm: 4.0,
          etaMinutes: 10,
          status: 'pending',
        },
      ],
      totalDistanceKm: 10.0,
      estimatedFuelLitres: 0,
      actualEnergyKwh: 18.5,
      co2SavedKg: 42.1,
      efficiencyScore: 98.1,
      activeWaypointIndex: 0,
      aiOptimizationRationale: 'Suburban route cluster scheduled to complete school and community center bins prior to afternoon athletics peak.',
    },
  },
  {
    id: 'tech_campus',
    name: 'Apex Silicon Campus & Medical Quarter',
    tagline: 'University research laboratories, student unions, and biotech medical center',
    city: 'Apex Innovation Park',
    category: 'tech_campus',
    description: 'High-density research and academic quad requiring specialized e-waste and chemical hazard segregation. Autonomous micro-rovers coordinate pickup around class change intervals.',
    population: '38,000 researchers & scholars',
    dailyWasteEstKg: 12400,
    activeSensorsCount: 7,
    recommendedFleet: 'Unit Apex-Rover (Compact EV Compactor)',
    areaKm2: 4.6,
    accentColor: '#8b5cf6', // purple
    zones: [
      {
        name: 'AI & ROBOTICS LABS',
        points: '15,15 50,15 50,50 15,50',
        color: '#8b5cf6',
        fillOpacity: 0.18,
        labelCoords: { x: 18, y: 20 },
      },
      {
        name: 'BIOMEDICAL & HEALTH COMPLEX',
        points: '55,15 90,15 90,55 55,55',
        color: '#ec4899',
        fillOpacity: 0.16,
        labelCoords: { x: 60, y: 20 },
      },
      {
        name: 'STUDENT RESIDENCES & QUAD',
        points: '20,55 85,55 85,90 20,90',
        color: '#6366f1',
        fillOpacity: 0.15,
        labelCoords: { x: 25, y: 62 },
      },
    ],
    bins: [
      {
        id: 'TBIN-401',
        name: 'Robotics & Hardware Lab Annex',
        address: '101 Cyber Way',
        district: 'AI & ROBOTICS LABS',
        coords: { x: 30, y: 28, lat: 37.7650, lng: -122.4200 },
        fillLevel: 95,
        capacityLiters: 900,
        wasteType: 'hazardous',
        batteryLevel: 97,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 18:00',
        bidPriority: 'critical',
        temperatureC: 20.5,
        odorPpm: 5,
        lidStatus: 'closed',
        currentBidAmount: 96,
        sensorAlerts: ['High volume of lithium/e-waste parts detected'],
      },
      {
        id: 'TBIN-402',
        name: 'Biomedical Innovation Quad',
        address: '500 Life Science Drive',
        district: 'BIOMEDICAL & HEALTH COMPLEX',
        coords: { x: 70, y: 26, lat: 37.7680, lng: -122.4110 },
        fillLevel: 88,
        capacityLiters: 1100,
        wasteType: 'hazardous',
        batteryLevel: 92,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 15:30',
        bidPriority: 'high',
        temperatureC: 19.8,
        odorPpm: 8,
        lidStatus: 'closed',
        currentBidAmount: 85,
      },
      {
        id: 'TBIN-403',
        name: 'Student Dining Commons & Food Hall',
        address: '200 Campus Mall',
        district: 'STUDENT RESIDENCES & QUAD',
        coords: { x: 45, y: 72, lat: 37.7610, lng: -122.4160 },
        fillLevel: 91,
        capacityLiters: 1600,
        wasteType: 'organic',
        batteryLevel: 89,
        sensorStatus: 'optimal',
        lastEmptied: 'Today, 06:45',
        bidPriority: 'critical',
        temperatureC: 24.2,
        odorPpm: 38,
        lidStatus: 'open',
        currentBidAmount: 94,
        sensorAlerts: ['Lunch surge overflow detected'],
      },
      {
        id: 'TBIN-404',
        name: 'Quantum Computing Facility',
        address: '40 Quantum Circle',
        district: 'AI & ROBOTICS LABS',
        coords: { x: 22, y: 42, lat: 37.7630, lng: -122.4230 },
        fillLevel: 52,
        capacityLiters: 800,
        wasteType: 'recyclable',
        batteryLevel: 85,
        sensorStatus: 'optimal',
        lastEmptied: '2 days ago',
        bidPriority: 'normal',
        temperatureC: 18.0,
        odorPpm: 3,
        lidStatus: 'closed',
        currentBidAmount: 48,
      },
      {
        id: 'TBIN-405',
        name: 'Graduate Engineering Housing',
        address: '80 Scholars Court',
        district: 'STUDENT RESIDENCES & QUAD',
        coords: { x: 75, y: 78, lat: 37.7590, lng: -122.4090 },
        fillLevel: 68,
        capacityLiters: 1200,
        wasteType: 'general',
        batteryLevel: 93,
        sensorStatus: 'optimal',
        lastEmptied: 'Yesterday, 12:00',
        bidPriority: 'normal',
        temperatureC: 20.8,
        odorPpm: 12,
        lidStatus: 'closed',
        currentBidAmount: 64,
      },
    ],
    trucks: [
      {
        id: 'TRUCK-T01',
        name: 'Unit Apex-Rover',
        model: 'Volvo FE Autonomous Micro-Compactor',
        powertrain: 'Electric EV',
        maxPayloadKg: 5200,
        currentLoadKg: 1800,
        batteryLevel: 95,
        status: 'routing',
        coords: { x: 38, y: 32 },
        targetCoords: { x: 30, y: 28 },
        speedKmh: 18,
        assignedRouteId: 'ROUTE-APEX-01',
        completedPickups: 1,
        efficiencyRating: 98.8,
        roboticArmStatus: 'ready',
        driverAgentMode: 'autonomous',
      },
    ],
    initialRoute: {
      routeId: 'ROUTE-APEX-01',
      truckId: 'TRUCK-T01',
      truckName: 'Unit Apex-Rover (Electric Micro-Compactor)',
      scheduledDate: '2026-09-24',
      status: 'active',
      waypoints: [
        {
          id: 'TWP-1',
          binId: 'TBIN-401',
          binName: 'Robotics & Hardware Lab Annex',
          address: '101 Cyber Way',
          coords: { x: 30, y: 28 },
          fillLevelSnapshot: 95,
          wasteType: 'hazardous',
          estimatedWeightKg: 650,
          distanceFromPrevKm: 1.1,
          etaMinutes: 3,
          status: 'approaching',
        },
        {
          id: 'TWP-2',
          binId: 'TBIN-403',
          binName: 'Student Dining Commons & Food Hall',
          address: '200 Campus Mall',
          coords: { x: 45, y: 72 },
          fillLevelSnapshot: 91,
          wasteType: 'organic',
          estimatedWeightKg: 890,
          distanceFromPrevKm: 1.8,
          etaMinutes: 5,
          status: 'pending',
        },
        {
          id: 'TWP-3',
          binId: 'TBIN-402',
          binName: 'Biomedical Innovation Quad',
          address: '500 Life Science Drive',
          coords: { x: 70, y: 26 },
          fillLevelSnapshot: 88,
          wasteType: 'hazardous',
          estimatedWeightKg: 720,
          distanceFromPrevKm: 2.2,
          etaMinutes: 6,
          status: 'pending',
        },
      ],
      totalDistanceKm: 5.1,
      estimatedFuelLitres: 0,
      actualEnergyKwh: 9.4,
      co2SavedKg: 21.2,
      efficiencyScore: 99.2,
      activeWaypointIndex: 0,
      aiOptimizationRationale: 'Campus micro-compactor scheduled between morning research seminars to minimize campus pedestrian impact.',
    },
  },
];

